name: Deploy to Cloud Run

on:
  push:
    branches: [ main, master ]
    paths:
      - "src/**"
      - "Dockerfile"
      - ".github/workflows/deploy.yml"
  workflow_dispatch: {}

env:
  REGION: ${{ secrets.GCP_REGION }}                 # e.g. europe-central2
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}         # sweetbalancetgbotmenu
  SERVICE_NAME: ${{ secrets.CLOUD_RUN_SERVICE || 'telebot' }}
  IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/telebot-repo/telebot:github-${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_PAY_TOKEN: ${{ secrets.TELEGRAM_PAY_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Auth to GCP with SA JSON (no Cloud Build needed)
      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      # One-time APIs (можешь удалить после включения вручную)
      - name: Enable required APIs (one-time)
        run: |
          gcloud services enable run.googleapis.com artifactregistry.googleapis.com || true

      # Создадим репозиторий в Artifact Registry, если ещё нет
      - name: Ensure Artifact Registry repo
        run: |
          gcloud artifacts repositories describe telebot-repo --location=${{ env.REGION }} || \
          gcloud artifacts repositories create telebot-repo \
            --repository-format=docker \
            --location=${{ env.REGION }} \
            --description="Telegram bot repo"

      # Docker auth to Artifact Registry
      - name: Configure docker auth for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      # Build & push image locally in the runner (no Cloud Build)
      - name: Docker build
        run: docker build -t ${{ env.IMAGE }} .

      - name: Docker push
        run: docker push ${{ env.IMAGE }}

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars "Telegram__BotToken=${{ env.TELEGRAM_BOT_TOKEN }},Telegram__PaymentProviderToken=${{ env.TELEGRAM_PAY_TOKEN }},Telegram__Currency=EUR"

      - name: Output service URL
        id: url
        run: |
          URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} --region ${{ env.REGION }} --format='value(status.url)')
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "Service URL: $URL"

      - name: Set Telegram webhook
        if: ${{ env.TELEGRAM_BOT_TOKEN != '' }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/setWebhook" \
            -d "url=${{ steps.url.outputs.url }}/bot/${{ env.TELEGRAM_BOT_TOKEN }}" \
            && curl -s "https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/getWebhookInfo"
